# Generated by Django 5.2 on 2025-05-12 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="ruc",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El RUC debe tener exactamente 11 dígitos.",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="RUC",
            ),
        ),
    ]
