# Generated by Django 5.2 on 2025-05-12 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_managers_alter_customuser_ruc"),
        ("users", "0003_custom"),
    ]

    operations = []
