# Generated by Django 5.2 on 2025-05-12 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20250511_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, 'Debes ingresar más de 2 caracteres')], verbose_name='Puesto'),
        ),
    ]
