# Generated by Django 5.2 on 2025-05-12 22:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=45454545, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
